In [4]:
import pandas as pd
import numpy as np
anime = pd.read_csv('anime.csv')
rating = pd.read_csv('rating.csv')
anime_modified = anime.set_index('name')

In [5]:
df = pd.DataFrame([[1,'Bob', 'Builder'],
                  [2,'Sally', 'Baker'],
                  [3,'Scott', 'Candle Stick Maker']],
                columns=['id','name', 'occupation'])

In [6]:
rating[:10].to_csv('saved_ratings.csv', index=False)

In [10]:
anime.tail(1)

,anime_id,name,genre,type,episodes,rating,members
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          3 non-null      int64
 1   name        3 non-null      object
 2   occupation  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [16]:
df.describe()

        id
count  3.0
mean   2.0
std    1.0
min    1.0
25%    1.5
50%    2.0
75%    2.5
max    3.0

In [18]:
anime.type.value_counts()

type
TV         3787
OVA        3311
Movie      2348
Special    1676
ONA         659
Music       488
Name: count, dtype: int64

In [19]:
anime['genre'].tolist()

['Drama, Romance, School, Supernatural',
 'Action, Adventure, Drama, Fantasy, Magic, Military, Shounen',
 'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
 'Sci-Fi, Thriller',
 'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
 'Comedy, Drama, School, Shounen, Sports',
 'Action, Adventure, Shounen, Super Power',
 'Drama, Military, Sci-Fi, Space',
 'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
 'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
 'Drama, Fantasy, Romance, Slice of Life, Supernatural',
 'Drama, School, Shounen',
 'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
 'Action, Drama, Mecha, Military, Sci-Fi, Super Power',
 'Comedy, Drama, School, Shounen, Sports',
 'Adventure, Drama, Supernatural',
 'Drama, Music, Romance, School, Shounen',
 'Adventure, Fantasy, Historical, Mystery, Seinen, Slice of Life, Supernatural',
 'Fantasy, Slice of Life',
 'Action, Mecha, Military, School, Sci-Fi, Super Power',
 'Comedy, Drama, Shounen, Sports',
 'Action, Drama, Historical, Martial Arts, Romance, Samurai',
 'Action, Adventure, Comedy, Drama, Sci-Fi, Space',
 'Action, Comedy, Parody, Sci-Fi, Seinen, Super Power, Supernatural',
 'Action, Adventure, Fantasy',
 'Comedy, Mystery, Romance, School, Sci-Fi, Supernatural',
 'Comedy, Mystery, Romance, Supernatural, Vampire',
 'Adventure, Fantasy, Historical, Mystery, Seinen, Slice of Life, Supernatural',
 'Adventure, Fantasy, Historical, Mystery, Seinen, Slice of Life, Supernatural',
 'Action, Adventure, Comedy, Mecha, Sci-Fi',
 'Comedy, Drama, School, Shounen, Slice of Life',
 'Drama, Fantasy, Shoujo, Slice of Life, Supernatural',
 'Comedy, Drama, Shounen, Sports',
 'Adventure, Fantasy, Historical, Mystery, Seinen, Slice of Life, Supernatural',
 'Drama, Fantasy, Shoujo, Slice of Life, Supernatural',
 'Adventure, Drama, Fantasy, Romance',
 'Action, Fantasy, Supernatural, Thriller',
 'Action, Mystery, Supernatural, Vampire',
 'Drama, Horror, Mystery, Police, Psychological, Seinen, Thriller',
 'Comedy, Drama, Romance, Shounen',
 'Mystery, Police, Psychological, Supernatural, Thriller',
 'Comedy, Parody',
 'Action, Comedy, School, Shounen',
 'Comedy, Drama, School, Shounen, Sports',
 'Comedy, Drama, Shounen, Sports',
 'Action, Drama, Mystery, Romance, Supernatural, Thriller',
 'Drama, Fantasy, Shoujo, Slice of Life, Supernatural',
 'Psychological, Seinen, Sports',
 'Adventure, Fantasy, Historical, Mystery, Seinen, Slice of Life, Supernatural',
 'Mystery, Psychological, Seinen, Supernatural',
 'Mystery, Psychological, Romance',
 'Fantasy, Sci-Fi, Shounen, Slice of Life',
 'Comedy, Demons, Fantasy, Shoujo, Supernatural',
 'Drama, Historical, Seinen, Thriller',
 'Drama, Fantasy, Psychological, Thriller',
 'Action, Mecha, Sci-Fi, Space, Super Power',
 'Drama, Fantasy, Shoujo, Slice of Life, Supernatural',
 'Drama, Slice of Life, Supernatural',
 'Comedy, School, Shounen, Sports',
 'Sci-Fi, Thriller',
 'Drama, Romance, Shoujo, Supernatural',
 'Ecchi, School, Shounen',
 'Comedy, Sports',
 'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
 'Action, Adventure, Drama, Shounen, Supernatural',
 'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
 'Action, Horror, Military, Seinen, Supernatural, Vampire',
 'Action, Drama, Horror, Psychological, Sci-Fi, Seinen',
 'Drama, Historical, Josei',
 'Comedy, Sci-Fi, Seinen, Slice of Life, Space',
 'Adventure, Supernatural',
 'Drama, Historical',
 'Comedy, School, Shounen, Sports',
 'Comedy, Drama, Romance, Sports',
 'Action, Adventure, Comedy, Drama, Fantasy, Shounen, Super Power',
 'Action, Mecha, Military, Mystery, Police, Sci-Fi, Seinen',
 'Action, Adventure, Comedy, Drama, Shounen, Supernatural',
 'Action, Mystery, Romance, Supernatural, Thriller',
 'Action, Historical, Military, Seinen',
 'Comedy, Drama, School, Shounen, Sports',
 'Josei, Slice of Life',
 'Military, School',
 'Action, Comedy, Slice of Life, Supernatural',
 'Comedy, Drama, Music, Romance, Shoujo, Slice of Life',
 'Action, Comedy, Historical, Mystery, Seinen, Supernatural',
 'Adventure, Fantasy, Historical, Mystery, Seinen, Slice of Life, Supernatural',
 'Action, Drama, Fantasy, Shounen, Super Power',
 'Comedy, Drama, Romance, Shounen',
 'Comedy, Drama, Romance, School, Sports',
 'Romance, School, Shounen Ai, Slice of Life',
 'Action, Mecha, Sci-Fi',
 'Drama, Horror, Mystery, Sci-Fi, Supernatural',
 'Action, Drama, Military, Sci-Fi, Space',
 'Drama, Game, Josei, Slice of Life, Sports',
 'Action, Fantasy, Supernatural',
 'Action, Adventure, Shounen, Supernatural, Vampire',
 'Drama, Magic, Psychological, Thriller',
 'Comedy, School, Slice of Life',
 'Action, Police, Psychological, Sci-Fi',
 'Comedy, Slice of Life',
 'Comedy, School, Shounen, Sports',
 'Action, Adventure, Fantasy, Magic, Shounen',
 'Drama, Magic, Psychological, Thriller',
 'Comedy, Drama, Sports',
 'Action, Adventure, Comedy, Historical, Samurai, Shounen',
 'Ecchi, School, Shounen',
 'Action, Adventure, Historical, Martial Arts, Romance',
 'Drama, Magic, Psychological, Thriller',
 'Comedy, Drama, Sports',
 'Demons, Fantasy, Historical, Horror, Mystery, Seinen, Supernatural',
 'Comedy, Drama',
 'Drama, Sports',
 'Action, Adventure, Shounen, Super Power',
 'Action, Adventure, Shounen, Supernatural',
 'Drama, Josei, Music, Romance, School',
 'Adventure, Comedy, Supernatural',
 'Action, Mecha, Military, Police, Sci-Fi, Seinen',
 'Adventure, Fantasy',
 'Adventure, Comedy, Ecchi, Fantasy, Game, Supernatural',
 'Adventure, Drama, Historical, Slice of Life',
 'Action, Comedy, Demons, Fantasy, Martial Arts, School, Shounen',
 'Action, Adventure, Slice of Life',
 'Comedy, School, Shounen, Sports',
 'Comedy, Drama, Josei, Music, Romance, Slice of Life',
 'Adventure, Fantasy, Historical, Romance',
 'Action, Fantasy, Shoujo, Supernatural',
 'Sci-Fi, Thriller',
 'Action, Fantasy, Magic, Shounen, Supernatural',
 'Drama, Fantasy',
 'Mystery, Supernatural, Vampire',
 'Dementia, Drama, Mecha, Psychological, Sci-Fi',
 'Comedy, Romance, School, Slice of Life',
 'Adventure, Drama, Romance, Sci-Fi',
 'Action, Adventure, Drama, Fantasy, Romance, Shounen',
 'Comedy, Mystery, Supernatural',
 'Action, Adventure, Comedy, Historical, Romance, Samurai',
 'Action, Adventure, Historical, Samurai',
 'Adventure, Mystery, Police, Shounen',
 'Action, Fantasy, Magic, Shounen, Supernatural',
 'Comedy, Drama, Shounen, Sports',
 'Action, Mecha, Military, Sci-Fi, Shounen, Space',
 'Action, Adventure, Ecchi, Fantasy, Shounen, Supernatural',
 'Drama, Fantasy, Shoujo, Slice of Life, Supernatural',
 'Action, Adventure, Comedy, Drama, Fantasy, Shounen',
 'Mystery, Psychological, Supernatural, Thriller',
 'Action, Adventure, Shounen, Super Power',
 'Action, Adventure, Shounen, Super Power',
 'Comedy, Demons, Fantasy, Historical, Mystery, Shounen, Supernatural',
 'Comedy, Drama, Shounen, Sports',
 'Psychological, Seinen, Sports',
 'Comedy, Drama, Music, Shounen, Slice of Life',
 'Action, Adventure, Demons, Drama, Fantasy, Horror, Military, Romance, Seinen, Supernatural',
 'Action, Drama, Mystery, Sci-Fi, Space',
 'Drama, Shounen, Sports',
 'Action, Drama, Mecha, Military, Sci-Fi, Space',
 'Drama, Fantasy, Shoujo, Slice of Life, Supernatural',
 'Comedy, Drama, Psychological, Romance',
 'Adventure, Drama, Historical, Romance, Shoujo',
 'Comedy, Drama, Romance, School, Slice of Life',
 'Action, Comedy, Drama, School, Supernatural',
 'Mystery, Romance, Supernatural, Vampire',
 'Mystery, Seinen, Supernatural',
 'Comedy, Shounen, Sports',
 'Action, Adventure, Comedy, Drama, Fantasy, Shounen',
 'Comedy, Harem, Romance, School, Shoujo',
 'Action, Mystery, Police, Shounen',
 'Action, Mystery, Supernatural',
 'Comedy, Josei, Music, Romance',
 'Drama, Romance, Sci-Fi, Seinen, Space',
 'Music, Sci-Fi',
 'Adventure, Fantasy, Romance, Sci-Fi',
 'Action, Comedy, Historical, Parody, Sci-Fi',
 'Drama, Josei, Romance',
 'Action, Adventure, Comedy, Demons, Fantasy, Magic, Romance, Shounen, Supernatural',
 'Fantasy, Historical',
 'Action, Comedy, Shounen, Super Power',
 'Comedy, Demons, Fantasy, Historical, Shounen, Supernatural',
 'Adventure, Fantasy, Historical, Romance',
 'Action, Comedy, School, Shounen, Super Power',
 'Comedy, School, Shounen, Slice of Life',
 'Comedy, Drama, Romance, School, Slice of Life, Supernatural',
 'Comedy, Drama, Sports',
 'Action, Adventure, Martial Arts, Shounen, Super Power, Supernatural',
 'Comedy, School, Shounen',
 'Comedy, Romance, Shounen',
 'Comedy, School, Shounen, Slice of Life',
 'Drama, Psychological, Romance, Slice of Life',
 'Fantasy, Slice of Life, Supernatural',
 'Comedy, Drama, Shounen, Sports',
 'Drama, Mystery, Psychological',
 'Comedy, Romance, Slice of Life',
 'Action, Mecha, Police, Psychological, Sci-Fi, Seinen',
 'Comedy, Music, Slice of Life',
 'Action, School, Shounen, Sports',
 'Action, Comedy, Drama, Magic, Super Power',
 'Action, Adventure, Drama, Fantasy, Historical, Romance',
 'Sci-Fi, Thriller',
 'Comedy, Drama, Mystery, Psychological, Supernatural',
 'Action, Adventure, Demons, Drama, Fantasy, Horror, Military, Seinen, Supernatural',
 'Drama, Game, Mystery, Psychological, Thriller',
 'Action, Adventure, Comedy, Drama, Fantasy, Magic, Military, Shounen',
 'Game, Psychological, Seinen, Thriller',
 'Action, Adventure, Shounen, Super Power',
 'Action, Cars, Sci-Fi, Sports',
 'Drama, Game, Josei, Slice of Life, Sports',
 'Action, Mystery, Police, Shounen',
 'Action, Adventure, Comedy, Fantasy, Martial Arts, Shounen, Super Power',
 'Action, Fantasy, Magic, Shounen, Supernatural',
 'Drama, Romance, School',
 'Adventure, Drama, Fantasy, Romance, Slice of Life',
 'Drama, Fantasy, Romance',
 'Action, Dementia, Drama, Mecha, Psychological, Sci-Fi',
 'Action, Adventure, Comedy, Drama, Fantasy, Shounen',
 'Comedy, Drama',
 'Action, Comedy, Sci-Fi',
 'Mystery, Supernatural',
 'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
 'Drama, Magic, Psychological, Thriller',
 'Comedy, Drama, Romance, Shounen Ai',
 'Comedy, Drama, Romance, School',
 'Comedy, Romance, School',
 'Fantasy, Sci-Fi, Shounen, Slice of Life',
 'Action, Seinen',
 'Comedy, Drama, Romance, School, Slice of Life, Supernatural',
 'Comedy, Harem, Romance, Shounen, Supernatural',
 'Comedy, Sci-Fi',
 'Action, Comedy, Historical, Mystery, Seinen, Supernatural',
 'Action, Mystery, Police, Shounen',
 'Game, Psychological, Seinen, Thriller',
 'Cars, Seinen, Sports',
 'Adventure, Mystery, Romance, Sci-Fi',
 'Action, Adventure, Comedy, Drama, Fantasy, Shounen, Super Power',
 'Comedy, School, Shounen, Supernatural',
 'Comedy, Drama, Fantasy, Magic, Romance, Shoujo',
 'Comedy, Shounen, Sports',
 'Comedy, Demons, Fantasy, Romance, Shoujo, Supernatural',
 'Comedy, Drama, Romance, Shoujo',
 'Comedy, Drama, Shounen, Sports',
 'Drama, Mystery, Sci-Fi, Supernatural, Thriller',
 'Adventure, Comedy, Drama, Fantasy, Magic, Romance',
 'Comedy, Josei, Music, Romance, Slice of Life',
 'Action, Adventure, Comedy, Drama, Fantasy, Shounen, Super Power',
 'Comedy, Parody',
 'Comedy, Sci-Fi, Space',
 'Drama',
 'Comedy, Music',
 'Sci-Fi, Slice of Life',
 'Sci-Fi, Slice of Life',
 'Comedy, Romance, School, Shoujo',
 'Adventure, Sci-Fi, Shounen',
 'Psychological, Thriller',
 'Action, Mystery, Sci-Fi, Super Power',
 'Adventure, Comedy, Mystery, Police, Shounen',
 'Adventure, Comedy, Mystery, Police, Shounen',
 'Comedy, School, Shounen, Sports',
 'Action, Adventure, Comedy, Fantasy, Magic, Shounen',
 'Drama, Music, School',
 'Action, Adventure, Drama, Shounen, Supernatural',
 'Comedy, Drama, Romance, Slice of Life',
 'Comedy, School, Seinen, Slice of Life',
 'Action, Comedy, Martial Arts, School, Shounen',
 'Adventure, Drama, Mecha, Sci-Fi, Shounen',
 'Comedy, Romance, School',
 'Action, Cars, Drama, Seinen, Sports',
 'Comedy, Drama, Romance, Shounen Ai',
 'Drama, Historical, Romance',
 'Action, Historical, Military, Seinen',
 'Comedy, Josei, Slice of Life',
 'Action, Adventure, Fantasy, Magic, Shounen',
 'Action, Drama, Mecha, Military, Sci-Fi, Space',
 'Romance, School, Slice of Life',
 'Action, Adventure, Martial Arts, Shounen, Super Power, Supernatural',
 'Action, Adventure, Fantasy, Historical',
 'Action, Adventure, Comedy, Fantasy, Romance, Shoujo',
 'Adventure, Comedy, Mystery, Police, Shounen',
 'Action, Mystery, Supernatural',
 'Comedy, School, Slice of Life',
 'Drama, Shoujo',
 'Drama, Historical, Mystery, Romance',
 'Comedy, Drama, Shounen, Sports',
 'Action, Cars, Drama, Seinen, Sports',
 'Action, Comedy, School, Super Power',
 'Comedy, Romance, Shoujo',
 'Dementia, Drama, Horror, Psychological',
 'Comedy, Fantasy, Magic, Romance',
 'Sci-Fi, Seinen',
 'Action, Adventure, Drama, Fantasy, Magic, Mystery, Romance, Shounen, Supernatural',
 'Drama, Sports',
 'Action, Adventure, Comedy, Fantasy, Magic, Shounen',
 'Mecha, Military, Mystery, Police, Sci-Fi, Seinen',
 'Action, Adventure, Fantasy, Magic, Shounen',
 'Drama, Fantasy, Psychological, Shoujo',
 'Action, Comedy, Mecha',
 'Adventure, Comedy, Mystery, Police, Shounen',
 'Action, Mecha, Sci-Fi',
 'Action, Comedy, School',
 'Action, Drama, Military, Sci-Fi, Space',
 'Action, Drama, Mystery, Supernatural, Thriller',
 'Action, Drama, Mecha, Military, Sci-Fi, Space',
 'Comedy, Mystery, Supernatural',
 'Comedy, Mystery, Supernatural',
 'Action, Comedy, School, Shounen',
 'Fantasy, Sci-Fi, Shounen, Slice of Life',
 'Romance, School, Shounen, Sports',
 'Action, Adventure, Comedy, Shounen',
 'Action, Military, Sci-Fi, Space',
 'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
 'Adventure, Comedy, Shounen',
 'Action, Drama, Mecha, Sci-Fi, Space',
 'Comedy, Sports',
 'Adventure, Comedy, Drama, Fantasy, Historical, Romance',
 'Comedy, Drama, Romance, Shounen Ai',
 'Drama, Slice of Life, Supernatural',
 'Adventure, Comedy, Drama, Mystery, Sci-Fi',
 'Adventure, Drama, Mecha, Romance, Sci-Fi',
 'Action, Mecha, Mystery, Police, Psychological, Sci-Fi, Seinen',
 'Action, Comedy, Parody, Samurai',
 'Comedy, School, Slice of Life',
 'Comedy, Game, Shounen, Supernatural',
 'Romance, School, Shoujo, Slice of Life',
 'Comedy, Drama, Romance, School, Slice of Life, Supernatural',
 'Drama',
 'Adventure, Comedy, Drama, Fantasy, Magic, Romance, School, Shoujo',
 'Drama, Mystery, Romance, Supernatural',
 'Comedy, School, Shounen, Slice of Life',
 'Comedy, Drama, Josei, Romance',
 'Comedy, Drama, Romance, Shoujo',
 'Music, School, Slice of Life',
 'Fantasy, Magic',
 'Comedy, Drama, Romance, Shounen Ai',
 'Comedy, Romance, Slice of Life',
 'Action, Seinen',
 'Action, Mystery, Police, Shounen',
 'Action, Fantasy, Super Power',
 'Horror, Mystery, Psychological, Supernatural, Thriller',
 'Mystery, School, Slice of Life',
 'Adventure, Drama, Music, Sci-Fi',
 'Drama, Romance, Slice of Life, Supernatural',
 'Romance, School, Shoujo, Slice of Life',
 'Action, Adventure, Shounen, Supernatural',
 'Action, Fantasy, Seinen, Supernatural',
 'Comedy, Drama, Mystery, Psychological, Supernatural',
 'Action, Drama, Fantasy, Magic, Mystery, Psychological, Shounen',
 'Comedy, Shounen, Slice of Life',
 'Adventure, Comedy, Mystery, Police, Shounen',
 'Adventure, Comedy, Mystery, Police, Shounen',
 'Adventure, Comedy, Fantasy, Martial Arts, Shounen, Super Power',
 'Comedy, Drama, Slice of Life, Supernatural',
 'Comedy, Drama, Romance, Shounen Ai',
 'Action, Adventure, Fantasy, Magic, Supernatural',
 'Action, Shounen, Sports',
 'Adventure, Drama, Sci-Fi',
 'Action, Adventure, Comedy, Fantasy, Shounen, Super Power',
 'Action, Drama, Seinen, Thriller',
 'Comedy, Romance, Slice of Life',
 'Action, Sci-Fi, Super Power',
 'Drama, Romance, School, Shounen, Slice of Life, Sports',
 'Comedy, Drama, Shounen, Sports',
 'Action, Adventure, Horror, Military, Sci-Fi, Supernatural',
 'Action, Seinen',
 'Action, Mystery, Supernatural',
 'Action, Comedy, Historical, Parody, Samurai, Shounen',
 'School, Slice of Life, Sports',
 'Comedy, Shounen',
 'Action, Demons, Shounen, Supernatural',
 'Fantasy, Horror, Mystery, Psychological, Sci-Fi, Thriller',
 'Comedy, School, Shounen, Sports',
 'Comedy, Romance, School, Shounen',
 'Comedy, Drama, Romance, Shounen Ai',
 'Drama, Fantasy, Romance, Shoujo',
 'Drama, Romance, School, Slice of Life',
 'Action, Adventure, Drama, Shounen',
 'Action, Cars, Drama, Seinen, Sports',
 'Comedy, Music, School, Slice of Life',
 'Action, Adventure, Fantasy, Game, Magic, Shounen',
 'Comedy, Romance, Shounen Ai',
 'Adventure, Comedy, Demons, Fantasy, Magic',
 'Fantasy, Sci-Fi, Shounen, Slice of Life',
 'Adventure, Comedy, Mystery, Police, Shounen',
 'Action, Adventure, Comedy, Drama',
 'Action, Comedy, Historical, Mecha, Parody, Samurai, Sci-Fi, Shounen',
 'Adventure, Comedy, Romance, Shounen',
 'Comedy, Demons, Fantasy, Romance, Shoujo, Supernatural',
 'Drama, Mystery, Seinen, Supernatural',
 'Adventure, Drama, Mecha, Military, Romance, Sci-Fi',
 'Action, Adventure, Fantasy, Kids',
 'Comedy, Demons, Shounen, Supernatural',
 'Adventure, Drama, Psychological, Sci-Fi, Supernatural',
 'Action, Horror, Mystery, Seinen, Supernatural',
 'Action, Sci-Fi, Seinen',
 'Action, Comedy, Mystery, Shounen',
 'Action, Mystery, Supernatural',
 'Drama, Mystery, Romance',
 'Action, Mecha, Police, Psychological, Sci-Fi, Seinen',
 'Action, Mecha, Sci-Fi',
 'Adventure, Romance, Sci-Fi, Shounen, Space',
 'Action, Cars, Drama, Seinen, Sports',
 'Comedy, Harem, Romance, Shounen, Supernatural',
 'Action, Adventure, Shounen',
 'Comedy, Kids, Sci-Fi, Shounen',
 'Action, Comedy, Mystery, Super Power',
 'Comedy, Drama, Romance, School',
 'Adventure, Drama, Fantasy, Magic, Military, Shounen',
 'Comedy, Mystery, Supernatural',
 'Comedy, Drama, Romance, School, Shounen, Slice of Life',
 'Comedy, Sports',
 'Comedy, Romance, Shoujo',
 'Comedy, Drama, Slice of Life',
 'Action, Adventure, Psychological, Supernatural',
 'Comedy, Romance',
 'Comedy, Drama, Mystery, Psychological, Supernatural',
 'Drama, Romance, Slice of Life',
 'Action, Horror, Mystery, Psychological',
 'Drama, Military, Sci-Fi, Space',
 'Historical, Samurai, Seinen',
 'Fantasy',
 'Action, Comedy, Drama, Magic, Super Power',
 'Drama, Historical, Romance, Samurai, Shounen',
 'Comedy, School, Slice of Life',
 'Action, Adventure, Demons, Drama, Fantasy, Horror, Military, Seinen, Supernatural',
 'Action, Mystery, Sci-Fi, Super Power',
 'Action, Fantasy',
 'Action, Historical, Military, Sci-Fi, Space',
 'Game, Shounen',
 'Drama, Historical, Romance, Sci-Fi, Shounen Ai',
 'Action, Comedy, Ecchi, Fantasy, Harem, Mecha, School',
 'Comedy, Drama, Romance, Shounen Ai',
 'Comedy, Drama, Fantasy',
 'Comedy, Drama, Psychological, Seinen',
 'Action, Mecha, Military, Music, Romance, Sci-Fi, Space',
 'Adventure, Comedy, Fantasy, Shounen',
 'Action, Comedy, Shounen, Sports',
 'Action, Comedy, Sports',
 'Action, Comedy, Shounen, Sports',
 'Comedy, Drama, Music, Romance, Shoujo, Supernatural',
 'Drama, Harem, Psychological, Romance',
 'Horror, Mystery, Psychological, Supernatural',
 'Comedy, Drama, Romance, Shounen Ai',
 'Comedy, Drama, Mystery, Psychological',
 'Comedy, School, Shounen',
 'Action, Adventure, Comedy, Fantasy, Shounen, Supernatural',
 'Action, Comedy, Sci-Fi',
 'Drama, Fantasy, Mystery, Psychological, Slice of Life',
 'Comedy, School, Shounen, Sports',
 'Action, Mecha, Military, Music, Romance, Sci-Fi, Space',
 'Action, Mystery, Psychological, Shounen, Supernatural, Thriller',
 'Action, Adventure, Drama, Fantasy, Shoujo',
 'Comedy, Parody, Seinen, Super Power',
 'Action, Drama, Military, Sci-Fi, Space',
 'Action, Drama, Horror, Mystery, Psychological, Seinen, Supernatural',
 'Josei, Slice of Life',
 'Kids, School, Shoujo',
 'Comedy, School, Slice of Life',
 'Drama, Slice of Life, Supernatural',
 'Adventure, Comedy, Mystery, Police, Shounen',
 'Action, Adventure, Comedy, Fantasy, Historical, Samurai, Seinen',
 'Action, Comedy, Dementia, Mecha, Parody, Sci-Fi',
 'Action, Mecha, Military',
 'Action, Comedy, Demons, Fantasy, Historical, Shounen, Supernatural',
 'Music, School, Slice of Life',

In [20]:
anime['genre']

0                     Drama, Romance, School, Supernatural
1        Action, Adventure, Drama, Fantasy, Magic, Mili...
2        Action, Comedy, Historical, Parody, Samurai, S...
3                                         Sci-Fi, Thriller
4        Action, Comedy, Historical, Parody, Samurai, S...
                               ...
12289                                               Hentai
12290                                               Hentai
12291                                               Hentai
12292                                               Hentai
12293                                               Hentai
Name: genre, Length: 12294, dtype: object

In [21]:
anime_modified.index.tolist()

['Kimi no Na wa.',
 'Fullmetal Alchemist: Brotherhood',
 'Gintama°',
 'Steins;Gate',
 'Gintama&#039;',
 'Haikyuu!!: Karasuno Koukou VS Shiratorizawa Gakuen Koukou',
 'Hunter x Hunter (2011)',
 'Ginga Eiyuu Densetsu',
 'Gintama Movie: Kanketsu-hen - Yorozuya yo Eien Nare',
 'Gintama&#039;: Enchousen',
 'Clannad: After Story',
 'Koe no Katachi',
 'Gintama',
 'Code Geass: Hangyaku no Lelouch R2',
 'Haikyuu!! Second Season',
 'Sen to Chihiro no Kamikakushi',
 'Shigatsu wa Kimi no Uso',
 'Mushishi Zoku Shou 2nd Season',
 'Ookami Kodomo no Ame to Yuki',
 'Code Geass: Hangyaku no Lelouch',
 'Hajime no Ippo',
 'Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-hen',
 'Cowboy Bebop',
 'One Punch Man',
 'Mononoke Hime',
 'Suzumiya Haruhi no Shoushitsu',
 'Monogatari Series: Second Season',
 'Mushishi Zoku Shou',
 'Mushishi',
 'Tengen Toppa Gurren Lagann',
 'Great Teacher Onizuka',
 'Natsume Yuujinchou Go',
 'Hajime no Ippo: New Challenger',
 'Mushishi Zoku Shou: Suzu no Shizuku',
 'Natsume Yuujinchou Shi',
 'Howl no Ugoku Shiro',
 'Fate/Zero 2nd Season',
 'Kizumonogatari II: Nekketsu-hen',
 'Monster',
 'Bakuman. 3rd Season',
 'Death Note',
 'Gintama°: Aizome Kaori-hen',
 'Ansatsu Kyoushitsu (TV) 2nd Season',
 'Haikyuu!!',
 'Hajime no Ippo: Rising',
 'Kara no Kyoukai 5: Mujun Rasen',
 'Natsume Yuujinchou San',
 'Ping Pong The Animation',
 'Mushishi Special: Hihamukage',
 'Boku dake ga Inai Machi',
 'Yojouhan Shinwa Taikei',
 'Aria The Origination',
 'Kamisama Hajimemashita: Kako-hen',
 'Rainbow: Nisha Rokubou no Shichinin',
 'Re:Zero kara Hajimeru Isekai Seikatsu',
 'Tengen Toppa Gurren Lagann Movie: Lagann-hen',
 'Zoku Natsume Yuujinchou',
 'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.',
 'Kuroko no Basket 3rd Season',
 'Steins;Gate Movie: Fuka Ryouiki no Déjà vu',
 'Hotarubi no Mori e',
 'Shokugeki no Souma',
 'Yuri!!! on Ice',
 'Gintama: Yorinuki Gintama-san on Theater 2D',
 'JoJo no Kimyou na Bouken: Stardust Crusaders 2nd Season',
 'Gintama Movie: Shinyaku Benizakura-hen',
 'Hellsing Ultimate',
 'Kiseijuu: Sei no Kakuritsu',
 'Shouwa Genroku Rakugo Shinjuu',
 'Uchuu Kyoudai',
 'Bakemono no Ko',
 'Hotaru no Haka',
 'Kuroko no Basket 2nd Season',
 'Major S5',
 'One Piece',
 'Ghost in the Shell: Stand Alone Complex 2nd GIG',
 'JoJo no Kimyou na Bouken: Diamond wa Kudakenai',
 'Kara no Kyoukai 7: Satsujin Kousatsu (Kou)',
 'Kingdom 2nd Season',
 'Slam Dunk',
 'Usagi Drop',
 'Girls und Panzer der Film',
 'Mob Psycho 100',
 'Nana',
 'Baccano!',
 'Mushishi Zoku Shou: Odoro no Michi',
 'Shingeki no Kyojin',
 'Bakuman. 2nd Season',
 'Cross Game',
 'Doukyuusei (Movie)',
 'Evangelion: 2.0 You Can (Not) Advance',
 'Shinsekai yori',
 'Uchuu Senkan Yamato 2199',
 'Chihayafuru 2',
 'Fate/Zero',
 'JoJo no Kimyou na Bouken (TV)',
 'Mahou Shoujo Madoka★Magica',
 'Nichijou',
 'Psycho-Pass',
 'Barakamon',
 'Diamond no Ace: Second Season',
 'Magi: The Kingdom of Magic',
 'Mahou Shoujo Madoka★Magica Movie 3: Hangyaku no Monogatari',
 'Major: World Series',
 'Samurai Champloo',
 'Shokugeki no Souma: Ni no Sara',
 'Katanagatari',
 'Mahou Shoujo Madoka★Magica Movie 2: Eien no Monogatari',
 'Major S6',
 'Mononoke',
 'Shirobako',
 'Ashita no Joe 2',
 'Hunter x Hunter',
 'Noragami Aragoto',
 'Sakamichi no Apollon',
 'Tonari no Totoro',
 'Ghost in the Shell: Stand Alone Complex',
 'Kaze no Tani no Nausicaä',
 'No Game No Life',
 'Romeo no Aoi Sora',
 'Yuu☆Yuu☆Hakusho',
 'Kino no Tabi: The Beautiful World',
 'Kuroko no Basket',
 'Nodame Cantabile',
 'Ookami to Koushinryou II',
 'Shingeki no Kyojin: Kuinaki Sentaku',
 'Steins;Gate: Oukoubakko no Poriomania',
 'Fate/stay night: Unlimited Blade Works 2nd Season',
 'Kemono no Souja Erin',
 'Kizumonogatari I: Tekketsu-hen',
 'Neon Genesis Evangelion: The End of Evangelion',
 'Toradora!',
 'Toki wo Kakeru Shoujo',
 'Tsubasa: Tokyo Revelations',
 'Owarimonogatari',
 'Rurouni Kenshin: Meiji Kenkaku Romantan',
 'Stranger: Mukou Hadan',
 'Detective Conan Movie 06: The Phantom of Baker Street',
 'Fate/stay night: Unlimited Blade Works',
 'Major S1',
 'Mobile Suit Gundam: The Origin',
 'Nanatsu no Taizai',
 'Natsume Yuujinchou',
 'One Piece Film: Strong World',
 'Higurashi no Naku Koro ni Kai',
 'Hunter x Hunter OVA',
 'Hunter x Hunter: Greed Island Final',
 'Kuroshitsuji: Book of Murder',
 'Major S2',
 'One Outs',
 'Beck',
 'Berserk',
 'Cowboy Bebop: Tengoku no Tobira',
 'Major S3',
 'Mobile Suit Gundam Unicorn',
 'Natsume Yuujinchou: Itsuka Yuki no Hi ni',
 'NHK ni Youkoso!',
 'Rose of Versailles',
 'Sakurasou no Pet na Kanojo',
 'Angel Beats!',
 'Bakemonogatari',
 'Bungou Stray Dogs 2nd Season',
 'Hajime no Ippo: Champion Road',
 'One Piece Film: Z',
 'Ouran Koukou Host Club',
 'Detective Conan Movie 13: The Raven Chaser',
 'Durarara!!',
 'Nodame Cantabile Finale',
 'Planetes',
 'Shelter',
 'Tenkuu no Shiro Laputa',
 'Gintama: Shiroyasha Koutan',
 'Hachimitsu to Clover II',
 'InuYasha: Kanketsu-hen',
 'Kaguya-hime no Monogatari',
 'Katekyo Hitman Reborn!',
 'Kuroshitsuji: Book of Circus',
 'Ookami to Koushinryou',
 'Boku no Hero Academia',
 'Gin no Saji 2nd Season',
 'Little Busters!: Refrain',
 'Major: Message',
 'Saint Seiya: The Lost Canvas - Meiou Shinwa 2',
 'SKET Dance',
 'Bakuman.',
 'Danshi Koukousei no Nichijou',
 'Kotonoha no Niwa',
 'Kyoukai no Kanata Movie: I&#039;ll Be Here - Mirai-hen',
 'Major S4',
 'Omoide no Marnie',
 'Working!!!: Lord of the Takanashi',
 'Ghost in the Shell',
 'K-On! Movie',
 'Kuroko no Basket: Saikou no Present Desu',
 'Mahou Shoujo Lyrical Nanoha: The Movie 2nd A&#039;s',
 'Sennen Joyuu',
 'Steins;Gate: Kyoukaimenjou no Missing Link - Divide By Zero',
 'xxxHOLiC Kei',
 'Berserk: Ougon Jidai-hen III - Kourin',
 'Death Parade',
 'Fullmetal Alchemist',
 'Gyakkyou Burai Kaiji: Ultimate Survivor',
 'Hunter x Hunter: Greed Island',
 'Redline',
 'Chihayafuru',
 'Detective Conan Movie 20: The Darkest Nightmare',
 'Dragon Ball Z',
 'Fate/stay night: Unlimited Blade Works - Prologue',
 'Kokoro ga Sakebitagatterunda.',
 'Mimi wo Sumaseba',
 'Nagi no Asukara',
 'Neon Genesis Evangelion',
 'One Piece Film: Gold',
 'Tokyo Godfathers',
 'Trigun',
 'xxxHOLiC Rou',
 'Gintama: Shinyaku Benizakura-hen',
 'Mahou Shoujo Madoka★Magica Movie 1: Hajimari no Monogatari',
 'Sekaiichi Hatsukoi 2',
 'Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku',
 'Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku OVA',
 'Aria The Natural',
 'Black Lagoon: The Second Barrage',
 'Clannad',
 'Kami nomi zo Shiru Sekai: Megami-hen',
 'Summer Wars',
 'Baccano! Specials',
 'Detective Conan Movie 14: The Lost Ship in the Sky',
 'Gyakkyou Burai Kaiji: Hakairoku-hen',
 'Initial D Final Stage',
 'Kaiba',
 'One Piece: Episode of Merry - Mou Hitori no Nakama no Monogatari',
 'Saiki Kusuo no Ψ-nan (TV)',
 'Cardcaptor Sakura Movie 2: Fuuin Sareta Card',
 'Hajime no Ippo: Mashiba vs. Kimura',
 'Kamisama Hajimemashita◎',
 'Skip Beat!',
 'Yowamushi Pedal: Grande Road',
 'Gankutsuou',
 'Majo no Takkyuubin',
 'Nodame Cantabile: Paris-hen',
 'One Piece: Episode of Nami - Koukaishi no Namida to Nakama no Kizuna',
 'Osomatsu-san',
 'Space☆Dandy 2nd Season',
 'Tsumiki no Ie',
 'Detroit Metal City',
 'Eve no Jikan',
 'Eve no Jikan (Movie)',
 'Kaichou wa Maid-sama!',
 'Saint Seiya: Meiou Hades Juuni Kyuu-hen',
 'Zankyou no Terror',
 'Darker than Black: Kuro no Keiyakusha',
 'Detective Conan',
 'Detective Conan Movie 05: Countdown to Heaven',
 'Diamond no Ace',
 'Fairy Tail (2014)',
 'Hibike! Euphonium 2',
 'JoJo no Kimyou na Bouken: Stardust Crusaders',
 'Maison Ikkoku',
 'Non Non Biyori Repeat',
 'Shijou Saikyou no Deshi Kenichi',
 'Yuusha-Ou GaoGaiGar Final',
 'Gekkan Shoujo Nozaki-kun',
 'Initial D Fourth Stage',
 'Junjou Romantica 2',
 'Kaze Tachinu',
 'Kingdom',
 'Kuragehime',
 'Magi: The Labyrinth of Magic',
 'Mobile Suit Gundam 00',
 'ReLIFE',
 'Saint Seiya: The Lost Canvas - Meiou Shinwa',
 'Seirei no Moribito',
 'Akatsuki no Yona',
 'Detective Conan Movie 08: Magician of the Silver Sky',
 'Durarara!!x2 Ketsu',
 'Free!: Eternal Summer Special',
 'Glass no Kamen (2005)',
 'Gosick',
 'Hajime no Ippo: Boxer no Kobushi',
 'Initial D First Stage',
 'Kill la Kill',
 'Lovely★Complex',
 'Perfect Blue',
 'Princess Tutu',
 'Sakasama no Patema',
 'Tsubasa: Shunraiki',
 'Ashita no Joe',
 'Fairy Tail',
 'Ghost in the Shell: Stand Alone Complex - Solid State Society',
 'Magi: Sinbad no Bouken (TV)',
 'Shoujo Kakumei Utena',
 'Tengen Toppa Gurren Lagann Movie: Gurren-hen',
 'Detective Conan Movie 10: Requiem of the Detectives',
 'Evangelion: 1.0 You Are (Not) Alone',
 'Full Metal Panic? Fumoffu',
 'Ginga Eiyuu Densetsu: Arata Naru Tatakai no Overture',
 'Kara no Kyoukai 3: Tsuukaku Zanryuu',
 'Mobile Suit Gundam 00 Second Season',
 'Nisemonogatari',
 'Tsukimonogatari',
 'Ansatsu Kyoushitsu (TV)',
 'Aria The Avvenire',
 'Baby Steps 2nd Season',
 'D.Gray-man',
 'Ginga Eiyuu Densetsu Gaiden: Senoku no Hoshi, Senoku no Hikari',
 'Gintama: Jump Festa 2014 Special',
 'Lupin III: Cagliostro no Shiro',
 'Mobile Suit Gundam: Iron-Blooded Orphans 2nd Season',
 'Ookiku Furikabutte: Natsu no Taikai-hen',
 'Saiunkoku Monogatari 2nd Season',
 'Sekaiichi Hatsukoi Movie: Yokozawa Takafumi no Baai',
 'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai. Movie',
 'Dennou Coil',
 'Eureka Seven',
 'Ghost in the Shell: Stand Alone Complex - The Laughing Man',
 'Gintama: Dai Hanseikai',
 'Hidamari Sketch: Sae Hiro Sotsugyou-hen',
 'Hikaru no Go',
 'Kimi ni Todoke',
 'Kokoro Connect: Michi Random',
 'Tokyo Magnitude 8.0',
 'Cardcaptor Sakura',
 'ef: A Tale of Melodies.',
 'Gin no Saji',
 'Hachimitsu to Clover',
 'Kodomo no Omocha (TV)',
 'Love Live! The School Idol Movie',
 'Mahoutsukai no Yome: Hoshi Matsu Hito',
 'Sekaiichi Hatsukoi OVA',
 'Working!!!',
 'Black Lagoon',
 'Detective Conan Movie 18: The Sniper from Another Dimension',
 'Final Fantasy VII: Advent Children Complete',
 'Higurashi no Naku Koro ni',
 'Hyouka',
 'Interstella5555: The 5tory of The 5ecret 5tar 5ystem',
 'Kanon (2006)',
 'Kimi ni Todoke 2nd Season',
 'Noragami',
 'Persona 3 the Movie 4: Winter of Rebirth',
 'xxxHOLiC Shunmuki',
 'Zetsuen no Tempest',
 'Aria The Origination: Sono Choppiri Himitsu no Basho ni...',
 'Detective Conan Movie 03: The Last Wizard of the Century',
 'Detective Conan Movie 04: Captured in Her Eyes',
 'Dragon Ball',
 'Hanada Shounen-shi',
 'Junjou Romantica 3',
 'Juuni Kokuki',
 'Major Movie: Yuujou no Winning Shot',
 'Mirai Shounen Conan',
 'One Piece Film: Strong World Episode 0',
 'Phantom: Requiem for the Phantom',
 'Tamako Love Story',
 'Toaru Kagaku no Railgun S',
 'Touch',
 'Yowamushi Pedal',
 'Akira',
 'Black Lagoon: Roberta&#039;s Blood Trail',
 'Durarara!!x2 Shou',
 'Gintama: Jump Festa 2015 Special',
 'High☆Speed!: Free! Starting Days',
 'Kyou kara Ore wa!!',
 'Nurarihyon no Mago: Sennen Makyou',
 'Paprika',
 'Prince of Tennis: The National Tournament Finals',
 'School Rumble Ni Gakki',
 'Sekaiichi Hatsukoi',
 'Akagami no Shirayuki-hime 2nd Season',
 'Clannad: Mou Hitotsu no Sekai, Tomoyo-hen',
 'Ginga Nagareboshi Gin',
 'Initial D Fifth Stage',
 'K-On!!',
 'Log Horizon',
 'Sekaiichi Hatsukoi: Valentine-hen',
 'Slayers Next',
 'Aria The OVA: Arietta',
 'Detective Conan Movie 15: Quarter of Silence',
 'Digimon Adventure tri. 3: Kokuhaku',
 'Gintama: Nanigoto mo Saiyo ga Kanjin nano de Tasho Senobisuru Kurai ga Choudoyoi',
 'Igano Kabamaru',
 'Kamisama Hajimemashita',
 'Kara no Kyoukai: Mirai Fukuin',
 'Mobile Suit Gundam: The 08th MS Team',
 'Omae Umasou da na',
 'Ushio to Tora (TV) 2nd Season',
 'Wolf&#039;s Rain OVA',
 'Ajin 2nd Season',
 'Aoki Hagane no Arpeggio: Ars Nova Cadenza',
 'City Hunter 2',
 'Durarara!!x2 Ten',
 'ef: A Tale of Memories.',
 'Ghost in the Shell 2.0',
 'Ghost in the Shell: Stand Alone Complex 2nd GIG - Individual Eleven',
 'Ginga Sengoku Gunyuuden Rai',
 'Initial D Second Stage',
 'Kami nomi zo Shiru Sekai II',
 'Noragami Aragoto OVA',
 'Stand By Me Doraemon',
 'Tiger &amp; Bunny',
 'Yahari Ore no Seishun Love Comedy wa Machigatteiru.',
 'Fullmetal Alchemist: Brotherhood Specials',
 'Hanamonogatari',
 'Kimi to Boku. 2',
 'Ookiku Furikabutte',
 'Ore Monogatari!!',
 'Tamayura: Sotsugyou Shashin Part 4 - Ashita',
 'Tekkon Kinkreet',
 'There She Is!!',
 'xxxHOLiC',
 'Byousoku 5 Centimeter',
 'Danganronpa 3: The End of Kibougamine Gakuen - Kibou-hen',
 'Ginga Eiyuu Densetsu Gaiden: Rasen Meikyuu',
 'Hyouge Mono',
 'Karigurashi no Arrietty',
 'Mahou Shoujo Lyrical Nanoha A&#039;s',
 'Rurouni Kenshin: Meiji Kenkaku Romantan - Seisou-hen',
 'Tanaka-kun wa Itsumo Kedaruge',
 'Berserk: Ougon Jidai-hen II - Doldrey Kouryaku',
 'Darker than Black: Kuro no Keiyakusha Gaiden',
 'Elsword: El Lady',
 'Ginga Eiyuu Densetsu: Waga Yuku wa Hoshi no Taikai',
 'Hikaru no Go: Journey to the North Star Cup',
 'Hybrid Child',
 'Isekai no Seikishi Monogatari',
 'Junjou Romantica OVA',
 'Kobato.',
 'Kuuchuu Buranko',
 'Macross: Do You Remember Love?',
 'One Piece 3D2Y: Ace no shi wo Koete! Luffy Nakama Tono Chikai',
 'Prince of Tennis: The National Tournament',
 'Prince of Tennis: The National Tournament Semifinals',
 'Eyeshield 21',
 'Full Moon wo Sagashite',
 'Grisaia no Rakuen',
 'Jigoku Shoujo Futakomori',
 'Junjou Romantica',
 'Mawaru Penguindrum',
 'SKET Dance OVA',
 'Soul Eater',
 'Trigun: Badlands Rumble',
 'Haibane Renmei',
 'Kuroko no Basket: Tip Off',
 'Macross',
 'Mirai Nikki (TV)',
 'Saiyuuki Reload: Burial',
 'Tentai Senshi Sunred 2nd Season',
 'Terra e... (TV)',
 'Tokyo Ghoul',
 'Usagi Drop Specials',
 'Yume-iro Pâtissière',
 'Azumanga Daioh',
 'Colorful (Movie)',
 'Detective Conan OVA 09: The Stranger in 10 Years...',
 'Drifters: Special Edition',
 'FLCL',
 'Full Metal Panic! The Second Raid',
 'Kuroshitsuji',
 'Love Live! School Idol Project 2nd Season',
 'Macross F Movie 2: Sayonara no Tsubasa',
 'Magi: Sinbad no Bouken',
 'Nekomonogatari: Kuro',
 'Saiunkoku Monogatari',
 'School Rumble',
 'Strike the Blood II',
 'Suzumiya Haruhi no Yuuutsu',
 'Flanders no Inu (Movie)',
 'Golden Boy',
 'Grisaia no Meikyuu: Caprice no Mayu 0',
 'Kaleido Star',
 'Kara no Kyoukai 4: Garan no Dou',
 'Lupin III vs. Detective Conan: The Movie',
 'Non Non Biyori',
 'Seitokai Yakuindomo* OVA',
 'Yakitate!! Japan',
 'Beelzebub',
 'Death Billiards',
 'Durarara!! Specials',
 'Jormungand: Perfect Order',
 'Mahou Shoujo Lyrical Nanoha: The Movie 1st',
 'Overlord',
 'Prince of Tennis',
 'Takarajima',
 'xxxHOLiC Movie: Manatsu no Yoru no Yume',
 'Yuru Yuri San☆Hai!',
 'Boruto: Naruto the Movie',
 'Coquelicot-zaka kara',
 'Eikoku Koi Monogatari Emma: Molders-hen',
 'Ergo Proxy',
 'Hanasaku Iroha',
 'Hataraku Maou-sama!',
 'Hibike! Euphonium',
 'Higashi no Eden',
 'Ie Naki Ko Remi',
 'Kono Subarashii Sekai ni Shukufuku wo!',
 'Kurenai no Buta',
 'Mobile Suit Zeta Gundam',
 'Prison School',
 'Saint Seiya',
 'Sayonara Zetsubou Sensei',
 'Seto no Hanayome OVA',
 'Zoku Sayonara Zetsubou Sensei',
 'Akachan to Boku',
 'Clannad: After Story - Mou Hitotsu no Sekai, Kyou-hen',
 'Hakuouki Movie 2: Shikon Soukyuu',
 'Kara no Kyoukai 2: Satsujin Kousatsu (Zen)',
 'Macross F',
 'Magic Kaito',
 'Sakigake!! Cromartie Koukou',
 'Shijou Saikyou no Deshi Kenichi OVA',
 'Touhai Densetsu Akagi: Yami ni Maiorita Tensai',
 'Carnival Phantasm',
 'D.Gray-man Hallow',
 'Date A Live: Encore OVA',
 'Dragon Ball Kai (2014)',
 'Gochuumon wa Usagi Desu ka??',
 'Hidamari Sketch x ☆☆☆',
 'Kokoro Connect',
 'Saiyuuki Gaiden',
 'Shirokuma Cafe',
 'Tiger &amp; Bunny Movie 2: The Rising',
 'Zan Sayonara Zetsubou Sensei',
 'City Hunter',
 'Detective Conan Movie 02: The Fourteenth Target',
 'Gekkan Shoujo Nozaki-kun Specials',
 'Giant Robo the Animation: Chikyuu ga Seishi Suru Hi',
 'Hetalia: The Beautiful World Specials',
 'Kaleido Star: Legend of Phoenix - Layla Hamilton Monogatari',
 'Kamisama Hajimemashita OVA',
 'Little Witch Academia',
 'Maria-sama ga Miteru 3rd',
 'Mobile Suit Gundam Thunderbolt',
 'The Everlasting Guilty Crown',
 'Bishoujo Senshi Sailor Moon: Sailor Stars',
 'Break Blade 4: Sanka no Chi',
 'Hanasaku Iroha: Home Sweet Home',
 'Hidamari Sketch x Honeycomb',
 'Hokuto no Ken',
 'Les Misérables: Shoujo Cosette',
 'Serial Experiments Lain',
 'Shiki',
 'Ushiro no Shoumen Daare',
 'Baka to Test to Shoukanjuu Ni!',
 'Detective Conan Movie 01: The Timed Skyscraper',
 'Detective Conan Movie 07: Crossroad in the Ancient Capital',
 'Gundam Build Fighters',
 'Hetalia: The Beautiful World',
 'Initial D Third Stage',
 'Kuroko no Basket 3rd Season NG-shuu',
 'Neko no Ongaeshi',
 'Seihou Bukyou Outlaw Star',
 'White Album 2',
 'Working&#039;!!',
 'Gate: Jieitai Kanochi nite, Kaku Tatakaeri',
 'Gate: Jieitai Kanochi nite, Kaku Tatakaeri 2nd Season',
 'Ghost Hunt',
 'Gungrave',
 'Jungle wa Itsumo Hare nochi Guu',
 'Kuroko no Basket 2nd Season NG-shuu',
 'Kyou kara Maou! 3rd Series',
 'Lupin III (2015)',
 'Madang-Eul Naon Amtalg',
 'Maria-sama ga Miteru 4th',
 'Musekinin Kanchou Tylor',
 'Ookami to Koushinryou II: Ookami to Kohakuiro no Yuuutsu',
 'Saint Seiya: Meiou Hades Meikai-hen',
 'Saint☆Oniisan (Movie)',
 'Seikai no Senki II',
 'Top wo Nerae! Gunbuster',
 'Toshokan Sensou: Kakumei no Tsubasa',
 'Uchouten Kazoku',
 'Baby Steps',
 'Break Blade 5: Shisen no Hate',
 'Code Geass: Hangyaku no Lelouch R2 Special Edition Zero Requiem',
 'Goku Sayonara Zetsubou Sensei',
 'Jormungand',
 'Kindaichi Shounen no Jikenbo (TV)',
 'Mobile Suit Gundam: Iron-Blooded Orphans',
 'Shin Mazinger Shougeki! Z-hen',
 'Tentai Senshi Sunred',
 'Yuusha-Ou GaoGaiGar',
 'Bleach',
 'Chuunibyou demo Koi ga Shitai!',
 'City Hunter 3',
 'Danganronpa 3: The End of Kibougamine Gakuen - Zetsubou-hen',
 'Detective Conan Movie 08: Time Travel of the Silver Sky',
 'Detective Conan OVA 10: Kid in Trap Island',
 'Dragon Ball Kai',
 'Hetalia World Series',
 'Jungle wa Itsumo Hare nochi Guu Deluxe',
 'Kami nomi zo Shiru Sekai',
 'Kyousou Giga (TV)',
 'Magic Kaito 1412',
 'Nejimaki Seirei Senki: Tenkyou no Alderamin',
 'Plastic Memories',
 'Psycho-Pass Movie',
 'Seto no Hanayome',
 'Sidonia no Kishi: Daikyuu Wakusei Seneki',
 'Tanoshii Muumin Ikka',
 'Tasogare Otome x Amnesia',
 'Vampire Hunter D (2000)',
 'Yuru Yuri Nachuyachumi!',
 'Break Blade 3: Kyoujin no Ato',
 'Danshi Koukousei no Nichijou Specials',
 'Detective Conan Movie 09: Strategy Above the Depths',
 'Detective Conan Movie 12: Full Score of Fear',
 'Final Fantasy VII: Advent Children',
 'Free!: Eternal Summer',
 'Hakuouki Movie 1: Kyoto Ranbu',
 'Hidamari Sketch x ☆☆☆ Specials',
 'K: Missing Kings',
 'Last Exile',
 'Little Busters!: EX',
 'Mobile Suit Gundam Wing: Endless Waltz Movie',
 'Naruto: Shippuuden',
 'Pokemon: The Origin',
 'Yuru Yuri♪♪',
 'Zan Sayonara Zetsubou Sensei Bangaichi',
 '3-gatsu no Lion',
 '91 Days',
 'Akagami no Shirayuki-hime',
 'Drifters',
 'Gake no Ue no Ponyo',
 'Ghost in the Shell 2: Innocence',
 'Haikyuu!! Movie 1: Owari to Hajimari',
 'Haikyuu!! OVA',
 'Hoozuki no Reitetsu OVA',
 'Keroro Gunsou',
 'Lupin III: Part II',
 'Macross F Movie 1: Itsuwari no Utahime',
 'Mobile Suit Gundam Seed',
 'Nodame Cantabile Finale Special',
 'Paradise Kiss',
 'Saint Seiya: The Hades Chapter Sanctuary - Yomigaerishi Gold Saint-tachi no Shinwa',
 'Saraiya Goyou',
 'Shiki Specials',
 'Slayers Try',
 'To LOVE-Ru Darkness 2nd Specials',
 'Transformers the Movie',
 'Uchuu Senkan Yamato 2199: Hoshimeguru Hakobune',
 'Wolf&#039;s Rain',
 'Akatsuki no Yona OVA',
 'Ao no Exorcist',
 'Claymore',
 'Detective Conan: Episode One - Chiisaku Natta Meitantei',
 'Ghost in the Shell: Stand Alone Complex - Solid State Society 3D',
 'Golden Time',
 'Hadashi no Gen',
 'Hayate no Gotoku!!',
 'Jinrui wa Suitai Shimashita',
 'Kyoukai no Kanata Movie: I&#039;ll Be Here - Kako-hen - Yakusoku no Kizuna',
 'Little Witch Academia: Mahoujikake no Parade',
 'Lucky☆Star: Original na Visual to Animation',
 'New Initial D Movie: Legend 1 - Kakusei',
 'Pandora Hearts',
 'Rurouni Kenshin DVD-BOX Special Ending',
 'Berserk: Ougon Jidai-hen I - Haou no Tamago',
 'Capeta',
 'Charlotte',
 'City Hunter &#039;91',
 'Kino no Tabi: Nanika wo Suru Tame ni - Life Goes On.',

In [22]:
anime_modified.columns.tolist()

['anime_id', 'genre', 'type', 'episodes', 'rating', 'members']

In [23]:
df['data'] = 10

In [24]:
anime[['name', 'genre']]

,name,genre
0,Kimi no Na wa.,"Drama, Romance, School, Supernatural"
1,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili..."
2,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S..."
3,Steins;Gate,"Sci-Fi, Thriller"
4,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S..."
...,...,...
12289,Toushindai My Lover: Minami tai Mecha-Minami,Hentai
12290,Under World,Hentai
12291,Violence Gekiga David no Hoshi,Hentai
12292,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai
12293,Yasuji no Pornorama: Yacchimae!!,Hentai

In [25]:
anime.drop(['anime_id', 'genre', 'members'], axis=1).head()

                               name   type episodes  rating
0                    Kimi no Na wa.  Movie        1    9.37
1  Fullmetal Alchemist: Brotherhood     TV       64    9.26
2                          Gintama°     TV       51    9.25
3                       Steins;Gate     TV       24    9.17
4                     Gintama&#039;     TV       51    9.16

In [27]:
df = pd.DataFrame([[1,'Bob', 8000],
                  [2,'Sally', 9000],
                  [3,'Scott', 20]], columns=['id','name', 'power level'])

In [30]:
df._append(df.sum(axis=0), ignore_index=True)

   id           name  power level
0   1            Bob         8000
1   2          Sally         9000
2   3          Scott           20
3   6  BobSallyScott        17020

In [31]:
df1 = anime[0:2]
df2 = anime[2:4]
pd.concat([df1, df2], ignore_index=True)

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572

In [32]:
rating.merge(anime, left_on='anime_id', right_on='anime_id', suffixes=('_left', '_right'))

,user_id,anime_id,rating_left,name,genre,type,episodes,rating_right,members
0,1,20,-1,Naruto,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,220,7.81,683297
1,1,24,-1,School Rumble,"Comedy, Romance, School, Shounen",TV,26,8.06,178553
2,1,79,-1,Shuffle!,"Comedy, Drama, Ecchi, Fantasy, Harem, Magic, R...",TV,24,7.31,158772
3,1,226,-1,Elfen Lied,"Action, Drama, Horror, Psychological, Romance,...",TV,13,7.85,623511
4,1,241,-1,Girls Bravo: First Season,"Comedy, Ecchi, Fantasy, Harem, Romance, School",TV,11,6.69,84395
...,...,...,...,...,...,...,...,...,...
7813722,73515,16512,7,Devil Survivor 2 The Animation,"Action, Demons, Supernatural",TV,13,7.06,101266
7813723,73515,17187,9,Ghost in the Shell: Arise - Border:1 Ghost Pain,"Mecha, Police, Psychological, Sci-Fi",Movie,1,7.64,31747
7813724,73515,22145,10,Kuroshitsuji: Book of Circus,"Comedy, Demons, Fantasy, Historical, Shounen, ...",TV,10,8.37,122895
7813725,73516,790,9,Ergo Proxy,"Mystery, Psychological, Sci-Fi",TV,23,8.03,265005
7813726,73516,8074,9,Highschool of the Dead,"Action, Ecchi, Horror, Supernatural",TV,12,7.46,535892

In [33]:
anime_modified.loc[['Haikyuu!! Second Season','Gintama']]

,anime_id,genre,type,episodes,rating,members
name,,,,,,
Haikyuu!! Second Season,28891,"Comedy, Drama, School, Shounen, Sports",TV,25,8.93,179342
Gintama,918,"Action, Comedy, Historical, Parody, Samurai, S...",TV,201,9.04,336376

In [35]:
anime_modified.iloc[15:25]

,anime_id,genre,type,episodes,rating,members
name,,,,,,
Sen to Chihiro no Kamikakushi,199,"Adventure, Drama, Supernatural",Movie,1,8.93,466254
Shigatsu wa Kimi no Uso,23273,"Drama, Music, Romance, School, Shounen",TV,22,8.92,416397
Mushishi Zoku Shou 2nd Season,24701,"Adventure, Fantasy, Historical, Mystery, Seine...",TV,10,8.88,75894
Ookami Kodomo no Ame to Yuki,12355,"Fantasy, Slice of Life",Movie,1,8.84,226193
Code Geass: Hangyaku no Lelouch,1575,"Action, Mecha, Military, School, Sci-Fi, Super...",TV,25,8.83,715151
Hajime no Ippo,263,"Comedy, Drama, Shounen, Sports",TV,75,8.83,157670
Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-hen,44,"Action, Drama, Historical, Martial Arts, Roman...",OVA,4,8.83,129307
Cowboy Bebop,1,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824
One Punch Man,30276,"Action, Comedy, Parody, Sci-Fi, Seinen, Super ...",TV,12,8.82,552458
Mononoke Hime,164,"Action, Adventure, Fantasy",Movie,1,8.81,339556

In [36]:
anime[anime['type'].isin(['TV', 'Movie'])]

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
11738,3038,Senya Ichiya Monogatari,"Fantasy, Hentai",Movie,1,6.18,1394
11805,2755,Cleopatra,"Hentai, Historical",Movie,1,6.06,1709
12244,11141,Blue Seagull,"Action, Hentai",Movie,1,4.60,337
12258,20007,Hi Gekiga Ukiyoe Senya Ichiya,"Action, Hentai",Movie,1,1.92,129
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [37]:
anime[1:3]

,anime_id,name,genre,type,episodes,rating,members
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262

In [38]:
anime[anime['rating'] > 8]

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
10765,32230,Xi You Ji,"Adventure, Fantasy",TV,52,8.07,89
10786,26313,Yakusoku: Africa Mizu to Midori,"Drama, Kids",OVA,1,9.25,53
10793,28557,Yamete! Writer Asobi: Doubutsu Mura no Shoubou...,"Drama, Kids",OVA,1,8.67,40
10847,26097,Yume no Tsuzuki,"Drama, Kids",OVA,1,8.67,53
12251,33960,Chou Do M na Hentai Mesu-tachi Otokoton Chouky...,Hentai,OVA,Unknown,8.38,161

In [39]:
anime.sort_values('rating', ascending=False)

,anime_id,name,genre,type,episodes,rating,members
10464,33662,Taka no Tsume 8: Yoshida-kun no X-Files,"Comedy, Parody",Movie,1,10.00,13
10400,30120,Spoon-hime no Swing Kitchen,"Adventure, Kids",TV,Unknown,9.60,47
9595,23005,Mogura no Motoro,Slice of Life,Movie,1,9.50,62
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
9078,33607,Kahei no Umi,Historical,Movie,1,9.33,44
...,...,...,...,...,...,...,...
12274,34492,Nuki Doki! Tenshi to Akuma no Sakusei Battle -...,Hentai,OVA,Unknown,NaN,392
12279,34491,Sagurare Otome The Animation,Hentai,OVA,1,NaN,79
12280,34312,Saimin Class,Hentai,OVA,Unknown,NaN,240
12282,34388,Shikkoku no Shaga The Animation,Hentai,OVA,Unknown,NaN,195
12285,34399,Taimanin Asagi 3,"Demons, Hentai, Supernatural",OVA,Unknown,NaN,485

In [79]:
tmp_df = rating.copy()
tmp_df.sort_values('user_id', ascending=True, inplace=True)
tmp_df = tmp_df[tmp_df.user_id < 10]
tmp_df = tmp_df[tmp_df.anime_id < 30]
tmp_df = tmp_df[tmp_df.rating != -1]
pd.pivot_table(tmp_df, values='rating', index=['user_id'],
               columns=['anime_id'], aggfunc=np.sum, fill_value=0)

/tmp/ipykernel_14229/2357769461.py:6: FutureWarning: The provided callable <function sum at 0x7f872cb22ac0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(tmp_df, values='rating', index=['user_id'],

anime_id  6   15  17  18  20  22  24
user_id
3          0   0   0   0   8   0   0
5          8   6   6   6   6   5   1
7          0   0   0   0   0   7   0